spring:
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web.exposure.include: "*"

logging:
  level:
    org.springframework.cloud: warn
    org.springframework.jms: info
