server:
  port: 8082

spring:
  application:
    name: inventory-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  # Enable debug logging for gRPC
  main:
    log-startup-info: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/inventorydb}
    username: ${SPRING_DATASOURCE_USERNAME:inventory}
    password: ${SPRING_DATASOURCE_PASSWORD:inventory}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  artemis:
    broker-url: ${SPRING_ARTEMIS_BROKER_URL:tcp://localhost:61710}
    user: ${SPRING_ARTEMIS_USER:admin}
    password: ${SPRING_ARTEMIS_PASSWORD:admin}

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    version: ${app.version:0.0.1-SNAPSHOT}
    env: ${APP_ENV:local}

app:
  jms:
    queue-inventory-reserve: order.inventory.reserve
    queue-inventory-reserve-reply: order.inventory.reserve.reply

grpc:
  server:
    port: 9091
    # Enable gRPC server
    enabled: true
    # In-process server name (optional)
    in-process-name: inventory-grpc-server

# Enable debug logging for gRPC
logging:
  level:
    net.devh.boot.grpc: DEBUG
    io.grpc: INFO
    com.example.inventoryservice.grpc: DEBUG
