server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://pg-inventory:5432/inventorydb
    username: inventory
    password: inventory
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  artemis:
    broker-url: tcp://artemis:61616
    user: admin
    password: admin

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    version: ${app.version:0.0.1-SNAPSHOT}
    env: ${APP_ENV:docker}

app:
  jms:
    queue-inventory-reserve: order.inventory.reserve
    queue-inventory-reserve-reply: order.inventory.reserve.reply

grpc:
  server:
    port: 9091
