server:
  port: 8083

spring:
  application:
    name: shipping-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/shippingdb}
    username: ${SPRING_DATASOURCE_USERNAME:shipping}
    password: ${SPRING_DATASOURCE_PASSWORD:shipping}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  artemis:
    broker-url: ${SPRING_ARTEMIS_BROKER_URL:tcp://localhost:61710}
    user: ${SPRING_ARTEMIS_USER:admin}
    password: ${SPRING_ARTEMIS_PASSWORD:admin}

  # listeners use TOPIC (pub/sub)
  jms:
    pub-sub-domain: true

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    version: ${app.version:0.0.1-SNAPSHOT}
    env: ${APP_ENV:local}

app:
  jms:
    topic-order-events: order.events
