server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://pg-order:5432/orderdb
    username: order
    password: order
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  artemis:
    broker-url: tcp://artemis:61616
    user: admin
    password: admin

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    version: ${app.version:0.0.1-SNAPSHOT}
    env: ${APP_ENV:docker}

app:
  jms:
    queue-inventory-reserve: order.inventory.reserve
    queue-inventory-reserve-reply: order.inventory.reserve.reply
    topic-order-events: order.events
  # Use gRPC for inventory calls (true) or JMS (false)
  use-grpc: true
  grpc:
    auth-token: ${GRPC_AUTH_TOKEN:demo-token}

grpc:
  client:
    inventory-service:
      address: 'dns:///inventory-service:9091'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      # Allow client to start even if server is not available
      enableRetry: true
      # Don't fail on startup if server is unavailable
      enableKeepAliveWithoutCalls: true

